def dados():
    produtos = {
        "7891033835515": {
            "nome": "Gel Creme Redutor de Rugas Botik Retinol Puro 30g",
            "ingredientes": [
                "Água",
                "Propanodiol",
                "Triglicerídeo Caprílico/Cáprico",
                "Manteiga De Butyrospermum Parkii",
                "Hidrolisado De Amido Hidrogenado",
                "Dimeticona",
                "Copolímero De Acrilato De Hidroxietila/Taurato De Acriloildimetil Sódico",
                "Isoexadecano",
                "Alantoína",
                "Isoestearato De Peg-6",
                "Fenoxietanol",
                "Fragrância",
                "Trolamina",
                "Crospolímero De Acrilatos/Acrilato De Alquila C10-30",
                "Caprililglicol",
                "Tocoferol",
                "Glicerídeos Caprílico/Cáprico",
                "Retinol",
                "Polissorbato 80",
                "Polissorbato 20",
                "Ácido Linoleico",
                "Ácido Oleico",
                "Dimeticonol",
                "Polissorbato 60",
                "Levomenol",
                "Goma Xantana",
                "Crospolímero De Dimeticona",
                "Ppg-15 Estearil Éter",
                "Éter De Macrogol Monoestearílico",
                "Maltodextrina",
                "Butilenoglicol",
                "Edetato Dissódico",
                "Isoestearato De Sorbitana",
                "Extrato De Aphanizomenon Flos-Aquae",
                "Extrato Da Semente De Helianthus Annuus",
                "Laurato De Hesperitina",
                "Sorbato De Potássio",
                "Amarelo De Tartrazina",
                "Extrato De Coenochloris Signiensis",
                "Lecitina",
                "Ácido Láctico",
                "Alfa-Isometil Ionona",
                "Citronelol",
                "Geraniol",
                "Hidroxicitronelal",
                "Limoneno",
                "Linalol",
            ],
        },
        "1234567890123": {
            "nome": "Creme Hidratante Facial com Retinol 50g",
            "ingredientes": [
                "Água",
                "Glicerina",
                "Óleo de Semente de Jojoba",
                "Manteiga de Karité",
                "Dimeticona",
                "Ácido Hialurônico",
                "Polissorbato 20",
                "Caprililglicol",
                "Tocoferol",
                "Retinol",
                "Ácido Linoleico",
                "Isoestearato De Sorbitana",
                "Extrato De Camomila",
                "Lecitina",
                "Ácido Láctico",
                "Fenoxietanol",
                "Fragrância",
                "Limoneno",
            ],
        },
        "9876543210987": {
            "nome": "Loção Corporal Hidratante Sem Retinol 200ml",
            "ingredientes": [
                "Água",
                "Glicerina",
                "Óleo de Amêndoas Doces",
                "Triglicerídeo Caprílico/Cáprico",
                "Manteiga De Butyrospermum Parkii",
                "Cera de Abelha",
                "Dimeticona",
                "Crospolímero De Acrilatos",
                "Caprililglicol",
                "Tocoferol",
                "Polissorbato 60",
                "Isoestearato De Sorbitana",
                "Extrato De Aloe Vera",
                "Fenoxietanol",
                "Lecitina",
                "Fragrância",
                "Linalol",
                "Citronelol",
            ],
        },
    }

    return produtos
